[package]
name = "wesloom-render"
description = "wgpu-based renderer for wesloom: pipeline abstraction with automatic forward/deferred shader variant switching."
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
wesloom-core = { workspace = true }
wesl = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
