//! The same distance fields as [`crate::ui::msdf`], generated by a compute
//! pass.
//!
//! Generating a glyph's field is independent per pixel and per channel, which
//! is a compute shader's best case: a batch of glyphs becomes one dispatch,
//! one workgroup layer per glyph, and one readback. The CPU implementation
//! stays the reference — it needs no adapter, so it can be tested against a
//! brute-force distance field anywhere, and it is what runs when a device is
//! busy or missing.
//!
//! Which one runs is [`MsdfBackend`], chosen at runtime through
//! [`MsdfGenerator`]. The editor exposes it on the command line, because
//! "does this glyph look wrong on both paths" is the first question to ask
//! about a text bug ([ADR 0014](../../../../docs/adr/0014-msdf-text-with-an-own-generator-and-app-supplied-fonts.md)).
//!
//! The shader is `package::wxsl::msdf`, in the library the application
//! supplies (ADR 0009), and it is a transliteration of `ui::msdf`. The two
//! must agree; `crates/wxsl/tests/render_cube.rs` compares them glyph for
//! glyph on a real device.

use std::borrow::Cow;

use bytemuck::{Pod, Zeroable};
use wxsl_core::abi;
use wxsl_core::macros::MacroSet;

use crate::error::RenderError;
use crate::library::ShaderLibrary;
use crate::ui::msdf::{self, ColoredEdge, MsdfBitmap, MsdfRequest, Segment};
use crate::variants;

/// Which implementation generates a glyph's distance field.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum MsdfBackend {
    /// [`crate::ui::msdf`], on the CPU. Needs no device, and is the
    /// reference the GPU path is checked against — also why it is the
    /// default: an application that never picks a backend still gets one
    /// that works before there is even an adapter to ask for.
    #[default]
    Cpu,
    /// `package::wxsl::msdf`, as a compute pass.
    Gpu,
}

impl MsdfBackend {
    /// Both backends, in declaration order.
    pub const ALL: &'static [MsdfBackend] = &[MsdfBackend::Cpu, MsdfBackend::Gpu];

    /// The backend's name, as used on the command line and in labels.
    pub fn name(&self) -> &'static str {
        match self {
            MsdfBackend::Cpu => "cpu",
            MsdfBackend::Gpu => "gpu",
        }
    }

    /// Parse a backend from its [`MsdfBackend::name`].
    pub fn parse(text: &str) -> Option<Self> {
        match text.trim().to_ascii_lowercase().as_str() {
            "cpu" => Some(MsdfBackend::Cpu),
            "gpu" => Some(MsdfBackend::Gpu),
            _ => None,
        }
    }

    /// The other one, for a toggle key.
    pub fn toggled(&self) -> Self {
        match self {
            MsdfBackend::Cpu => MsdfBackend::Gpu,
            MsdfBackend::Gpu => MsdfBackend::Cpu,
        }
    }
}

/// One coloured edge, as the compute shader's `MsdfEdge`.
///
/// Unused control points repeat the endpoint so that every kind is one
/// stride. Host-shared with `shaders/wxsl/msdf.wxsl`: 40 bytes, `vec2f`
/// alignment, and the two are edited together.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
struct GpuEdge {
    points: [[f32; 2]; 4],
    kind: u32,
    color: u32,
}

impl GpuEdge {
    fn new(edge: &ColoredEdge) -> Self {
        let (kind, points) = match edge.segment {
            Segment::Line([a, b]) => (
                abi::MSDF_EDGE_LINE,
                [a.to_array(), b.to_array(), b.to_array(), b.to_array()],
            ),
            Segment::Quad([a, b, c]) => (
                abi::MSDF_EDGE_QUAD,
                [a.to_array(), b.to_array(), c.to_array(), c.to_array()],
            ),
            Segment::Cubic([a, b, c, d]) => (
                abi::MSDF_EDGE_CUBIC,
                [a.to_array(), b.to_array(), c.to_array(), d.to_array()],
            ),
        };
        GpuEdge {
            points,
            kind,
            color: edge.color.channels(),
        }
    }
}

/// One glyph to generate, as the compute shader's `MsdfJob`.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Pod, Zeroable)]
struct GpuJob {
    translate: [f32; 2],
    scale: f32,
    range: f32,
    size: [u32; 2],
    edge_begin: u32,
    edge_end: u32,
    pixel_offset: u32,
    _pad0: u32,
}

/// The compute pipeline that generates distance fields.
pub struct MsdfCompute {
    pipeline: wgpu::ComputePipeline,
    bind_group_layout: wgpu::BindGroupLayout,
    wgsl: String,
}

impl MsdfCompute {
    /// Compile `package::wxsl::msdf` from `library` and build the pipeline.
    ///
    /// Fails if the library has no such module, which is the same failure
    /// mode as a missing ABI module: the application supplies the shaders.
    pub fn new(device: &wgpu::Device, library: &ShaderLibrary) -> Result<Self, RenderError> {
        if !library.contains(abi::MSDF_MODULE) {
            return Err(RenderError::MissingModule {
                module: abi::MSDF_MODULE.to_string(),
            });
        }
        let extra: [(&str, Cow<'_, str>); 0] = [];
        let wgsl = variants::compile(library, &extra, abi::MSDF_MODULE, &MacroSet::new())?;
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("wxsl msdf"),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(wgsl.as_str())),
        });

        let storage = |binding: u32, read_only: bool| wgpu::BindGroupLayoutEntry {
            binding,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Storage { read_only },
                has_dynamic_offset: false,
                min_binding_size: None,
            },
            count: None,
        };
        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("wxsl msdf"),
            entries: &[
                storage(abi::BINDING_MSDF_EDGES, true),
                storage(abi::BINDING_MSDF_JOBS, true),
                storage(abi::BINDING_MSDF_PIXELS, false),
            ],
        });
        // Groups 0..2 are genuinely unbound: generating a distance field has
        // no camera, no material and no frame. The pass group is where a
        // pipeline shape's own resources go (ADR 0010).
        let layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("wxsl msdf"),
            bind_group_layouts: &[None, None, None, Some(&bind_group_layout)],
            immediate_size: 0,
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("wxsl msdf"),
            layout: Some(&layout),
            module: &module,
            entry_point: Some(abi::MSDF_ENTRY),
            compilation_options: Default::default(),
            cache: None,
        });
        Ok(MsdfCompute {
            pipeline,
            bind_group_layout,
            wgsl,
        })
    }

    /// The WGSL the compute pass compiled to.
    ///
    /// Same reason [`crate::variants::ShaderVariant::wgsl`] is kept: when a
    /// glyph comes out wrong, this is the only readable answer to what the
    /// GPU was actually running.
    pub fn wgsl(&self) -> &str {
        &self.wgsl
    }

    /// Generate every field in `requests`, in one dispatch and one readback.
    ///
    /// Blocks until the GPU is done, so call it once per batch of new glyphs
    /// rather than once per glyph. Returns the bitmaps in request order.
    pub fn generate(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        requests: &[MsdfRequest<'_>],
    ) -> Result<Vec<MsdfBitmap>, RenderError> {
        if requests.is_empty() {
            return Ok(Vec::new());
        }

        let mut edges: Vec<GpuEdge> = Vec::new();
        let mut jobs: Vec<GpuJob> = Vec::with_capacity(requests.len());
        let mut pixel_count: u32 = 0;
        let mut dispatch = [0u32, 0u32];
        for request in requests {
            let begin = edges.len() as u32;
            edges.extend(request.edges.iter().map(GpuEdge::new));
            jobs.push(GpuJob {
                translate: request.transform.translate.to_array(),
                scale: request.transform.scale,
                range: request.range.max(1e-3),
                size: [request.width, request.height],
                edge_begin: begin,
                edge_end: edges.len() as u32,
                pixel_offset: pixel_count,
                _pad0: 0,
            });
            pixel_count += request.width * request.height;
            dispatch[0] = dispatch[0].max(request.width);
            dispatch[1] = dispatch[1].max(request.height);
        }
        if pixel_count == 0 {
            // Every request is zero-sized (a blank glyph, say). Nothing to
            // dispatch, but the caller still expects one bitmap each.
            return Ok(requests
                .iter()
                .map(|request| MsdfBitmap {
                    width: request.width,
                    height: request.height,
                    range: request.range,
                    pixels: Vec::new(),
                })
                .collect());
        }
        // A zero-length storage buffer is a validation error, and a glyph
        // with no contours (a space) legitimately has no edges. One edge
        // writing no channel is inert: the shader skips it for every channel.
        if edges.is_empty() {
            edges.push(GpuEdge {
                points: [[0.0; 2]; 4],
                kind: abi::MSDF_EDGE_LINE,
                color: 0,
            });
        }

        use wgpu::util::DeviceExt as _;
        let edge_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("wxsl msdf edges"),
            contents: bytemuck::cast_slice(&edges),
            usage: wgpu::BufferUsages::STORAGE,
        });
        let job_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("wxsl msdf jobs"),
            contents: bytemuck::cast_slice(&jobs),
            usage: wgpu::BufferUsages::STORAGE,
        });
        let output_size = u64::from(pixel_count) * 4;
        let output = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("wxsl msdf pixels"),
            size: output_size,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        });
        let readback = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("wxsl msdf readback"),
            size: output_size,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("wxsl msdf"),
            layout: &self.bind_group_layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: abi::BINDING_MSDF_EDGES,
                    resource: edge_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: abi::BINDING_MSDF_JOBS,
                    resource: job_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: abi::BINDING_MSDF_PIXELS,
                    resource: output.as_entire_binding(),
                },
            ],
        });

        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("wxsl msdf"),
        });
        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("wxsl msdf"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&self.pipeline);
            pass.set_bind_group(abi::GROUP_PASS, &bind_group, &[]);
            let [group_x, group_y] = abi::MSDF_WORKGROUP;
            pass.dispatch_workgroups(
                dispatch[0].div_ceil(group_x),
                dispatch[1].div_ceil(group_y),
                jobs.len() as u32,
            );
        }
        encoder.copy_buffer_to_buffer(&output, 0, &readback, 0, output_size);
        queue.submit([encoder.finish()]);

        readback.slice(..).map_async(wgpu::MapMode::Read, |_| {});
        let _ = device.poll(wgpu::PollType::wait_indefinitely());
        let mapped = readback
            .slice(..)
            .get_mapped_range()
            .expect("the readback buffer is mapped after a blocking poll");
        let packed: &[u8] = &mapped;

        let mut bitmaps = Vec::with_capacity(requests.len());
        for (request, job) in requests.iter().zip(&jobs) {
            let count = (request.width * request.height) as usize;
            let start = job.pixel_offset as usize * 4;
            let mut pixels = Vec::with_capacity(count * 3);
            for texel in packed[start..start + count * 4].chunks_exact(4) {
                // Drop the opaque alpha the shader packed: an `MsdfBitmap` is
                // RGB, so that the two backends' output compares directly.
                pixels.extend_from_slice(&texel[..3]);
            }
            bitmaps.push(MsdfBitmap {
                width: request.width,
                height: request.height,
                range: request.range,
                pixels,
            });
        }
        drop(mapped);
        readback.unmap();
        Ok(bitmaps)
    }
}

/// A distance-field generator: whichever backend was selected.
///
/// The seam the glyph cache talks to, so that switching backend is one line
/// and both paths are exercised by the same code above them.
pub struct MsdfGenerator {
    backend: MsdfBackend,
    compute: Option<MsdfCompute>,
}

impl MsdfGenerator {
    /// A generator for `backend`, compiling the compute pass if it needs one.
    pub fn new(
        device: &wgpu::Device,
        library: &ShaderLibrary,
        backend: MsdfBackend,
    ) -> Result<Self, RenderError> {
        let compute = match backend {
            MsdfBackend::Cpu => None,
            MsdfBackend::Gpu => Some(MsdfCompute::new(device, library)?),
        };
        Ok(MsdfGenerator { backend, compute })
    }

    /// The CPU generator, which needs no device and cannot fail to build.
    pub fn cpu() -> Self {
        MsdfGenerator {
            backend: MsdfBackend::Cpu,
            compute: None,
        }
    }

    /// Which backend is in use.
    pub fn backend(&self) -> MsdfBackend {
        self.backend
    }

    /// The compute pass, if this generator has one.
    pub fn compute(&self) -> Option<&MsdfCompute> {
        self.compute.as_ref()
    }

    /// Generate every field in `requests`, on the selected backend.
    pub fn generate(
        &self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        requests: &[MsdfRequest<'_>],
    ) -> Result<Vec<MsdfBitmap>, RenderError> {
        match &self.compute {
            Some(compute) => compute.generate(device, queue, requests),
            None => Ok(requests.iter().map(msdf::generate_edges).collect()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backend_names_round_trip() {
        for backend in MsdfBackend::ALL {
            assert_eq!(MsdfBackend::parse(backend.name()), Some(*backend));
            assert_eq!(backend.toggled().toggled(), *backend);
        }
        assert_eq!(MsdfBackend::parse("  GPU "), Some(MsdfBackend::Gpu));
        assert_eq!(MsdfBackend::parse("cuda"), None);
    }

    #[test]
    fn the_default_backend_needs_no_device() {
        // An application that never picks a backend must still get one that
        // works before there is even an adapter to ask for — the CPU path,
        // not the one that needs a compiled compute pipeline.
        assert_eq!(MsdfBackend::default(), MsdfBackend::Cpu);
    }

    #[test]
    fn the_host_structs_match_the_layout_the_shader_declares() {
        // Both are 40 bytes with 8-byte alignment in WGSL's storage layout
        // rules; a mismatch would read every field but the first from the
        // wrong offset, which is a garbage glyph rather than an error.
        assert_eq!(core::mem::size_of::<GpuEdge>(), 40);
        assert_eq!(core::mem::size_of::<GpuJob>(), 40);
        assert_eq!(core::mem::size_of::<GpuEdge>() % 8, 0);
        assert_eq!(core::mem::size_of::<GpuJob>() % 8, 0);
    }

    #[test]
    fn every_segment_kind_maps_to_the_abi_edge_kind() {
        use crate::ui::msdf::EdgeColor;
        use glam::Vec2;

        let colored = |segment| ColoredEdge {
            segment,
            color: EdgeColor::WHITE,
        };
        let line = GpuEdge::new(&colored(Segment::Line([Vec2::ZERO, Vec2::X])));
        assert_eq!(line.kind, abi::MSDF_EDGE_LINE);
        // An unused control point repeats the endpoint, so the shader's
        // `msdf_end` finds the right point whatever the kind.
        assert_eq!(line.points[3], Vec2::X.to_array());

        let quad = GpuEdge::new(&colored(Segment::Quad([Vec2::ZERO, Vec2::X, Vec2::Y])));
        assert_eq!(quad.kind, abi::MSDF_EDGE_QUAD);
        assert_eq!(quad.points[3], Vec2::Y.to_array());

        let cubic = GpuEdge::new(&colored(Segment::Cubic([
            Vec2::ZERO,
            Vec2::X,
            Vec2::Y,
            Vec2::ONE,
        ])));
        assert_eq!(cubic.kind, abi::MSDF_EDGE_CUBIC);
        assert_eq!(cubic.points[3], Vec2::ONE.to_array());
    }

    #[test]
    fn the_cpu_generator_needs_no_device() {
        let generator = MsdfGenerator::cpu();
        assert_eq!(generator.backend(), MsdfBackend::Cpu);
        assert!(generator.compute().is_none());
    }
}
