//! Every stdlib function and operator as a `wxsl-core` node definition.
//!
//! Two kinds of node live here, and the split is deliberate:
//!
//! * **Operators** ([`math_nodes`], [`vector_nodes`], [`convert_nodes`],
//!   [`logic_nodes`], [`constant_nodes`]) are inline WXSL expressions over
//!   WGSL's own built-ins — `{a} + {b}`, `mix({a}, {b}, {t})`. Wrapping an
//!   addition in a function call would cost a WXSL module, an import and a
//!   call per node for no gain.
//! * **Functions** (everything else: colour, lighting, noise, SDFs, …) are
//!   calls to the `.wxsl` functions this crate ships, and none of them is
//!   written here at all. Each file *is* its node: [`derived_nodes`] is
//!   generated by `build.rs`, which runs `wxsl_lang::node_from_source` over
//!   every file under `shaders/<category>/`
//!   ([ADR 0020](../../../docs/adr/0020-a-node-definition-is-derived-from-its-wxsl-source.md)).
//!   Sockets, defaults, docs, type parameters and macro declarations all come
//!   from the signature and its comments, so a function and its node cannot
//!   disagree — there is nowhere for them to disagree.
//!
//! **One node per operation, not one per operation and type.** A definition
//! declares the types it works over as a [`GenericParam`] and its sockets
//! carry it, so `math.add` is one registry entry covering `f32` through
//! `mat4x4f`, resolved per graph node from whatever is connected — not
//! `math.add.f32`, `math.add.vec2f`, … as separate node kinds
//! ([ADR 0015](../../../docs/adr/0015-generic-sockets-for-arithmetic-nodes.md),
//! [ADR 0018](../../../docs/adr/0018-one-generic-node-per-operation.md)).
//! Where WGSL lets an operator's two operands differ — `f32 * vec3f`,
//! `mat3x3f * vec3f`, `vec3f + f32` — the node declares *two* parameters and
//! derives the result with a [`TypeRule`], which is the only way to say
//! "these two may legitimately differ". `crates/wxsl/tests/wgsl_types.rs`
//! checks those rules against `wgpu`'s validator, and is where the tables
//! below came from.
//!
//! A function whose WXSL reads a macro variable declares it there, with
//! `@macro const` (see `shaders/generative/fbm3.wxsl`), and the derivation
//! carries it onto the node. That is what puts the macro in a graph's
//! editable macro set, and what guarantees the generated macro module
//! declares it whenever the function is reachable.
//!
//! # Adding a function node
//!
//! Write the `.wxsl` file. There is no second step: `shaders/README.md` has
//! the authoring rules, and the file's own comments carry the label, the
//! documentation and the socket defaults.

use wxsl_core::abi;
use wxsl_core::macros::{MacroDef, MacroValue};
use wxsl_core::node::{
    self, GenericParam, NodeBody, NodeDefinition, NodeRegistry, SettingDef, Socket, TypeRule,
    Value, ValueType, WxslFunction,
};

/// Every node definition in the library, including the ABI's input and
/// output nodes.
pub fn all_nodes() -> Vec<NodeDefinition> {
    let mut defs = Vec::new();
    defs.extend(abi_nodes());
    defs.extend(constant_nodes());
    defs.extend(declaration_nodes());
    defs.extend(math_nodes());
    defs.extend(vector_nodes());
    defs.extend(convert_nodes());
    defs.extend(logic_nodes());
    defs.extend(derived_nodes());
    defs
}

// Every function node, derived from the `.wxsl` file that defines it. See
// `build.rs`.
include!(concat!(env!("OUT_DIR"), "/derived_nodes.rs"));

/// A registry holding [`all_nodes`].
///
/// This is what a graph is validated and compiled against; a consumer with
/// its own nodes registers them on top.
pub fn registry() -> NodeRegistry {
    let mut registry = NodeRegistry::new();
    registry.register_all(all_nodes());
    registry
}

/// The graph's entry and exit nodes, generated from the shader ABI: one
/// reader per [`abi::CONTEXT_FIELDS`] entry, and the surface output node.
pub fn abi_nodes() -> Vec<NodeDefinition> {
    let mut defs = abi::context_node_defs();
    defs.push(abi::surface_output_def());
    defs
}

// ---------------------------------------------------------------------------
// Socket helpers
// ---------------------------------------------------------------------------

fn out(ty: ValueType) -> Socket {
    Socket::new("out", ty)
}

fn scalar(name: &str, default: f32) -> Socket {
    Socket::new(name, ValueType::F32).with_default(Value::F32(default))
}

fn splat(name: &str, ty: ValueType, default: f32) -> Socket {
    Socket::new(name, ty).with_splat_default(default)
}

fn direction(name: &str, default: [f32; 3]) -> Socket {
    Socket::new(name, ValueType::Vec3).with_default(Value::Vec3(default))
}

/// A generic parameter named `name`, resolvable to any of `allowed`.
///
/// A free function rather than a `const` because [`GenericParam`] owns a
/// `Vec` (a `ValueType` slice turned into one), so it cannot be a `const`
/// itself.
fn param(name: &str, allowed: &[ValueType]) -> GenericParam {
    GenericParam::new(name, allowed.to_vec())
}

/// The single parameter `T` that most generic nodes declare: one type,
/// shared by every socket carrying it, resolved per graph node from
/// whatever is actually connected (or picked explicitly with
/// [`wxsl_core::graph::Graph::set_generic`]).
///
/// The nodes that do *not* use this shape are the ones whose operands WGSL
/// lets differ: those declare two parameters and derive the result with a
/// [`TypeRule`] — see [`BINARY`] and `vector.transform`.
fn shared(allowed: &[ValueType]) -> GenericParam {
    param("T", allowed)
}

/// A socket carrying [`shared`]'s `T`, with no default.
///
/// The placeholder `F32` is never read: codegen always asks the graph for
/// this node instance's *resolved* type instead (see
/// [`wxsl_core::node::Socket::generic`]).
fn generic_socket(name: &str) -> Socket {
    Socket::new(name, ValueType::F32).generic("T")
}

/// A socket carrying `T`, defaulting to `default` spread over whatever `T`
/// resolves to — `clamp`'s `high` is 1 at every width.
///
/// See [`wxsl_core::node::Socket::splat_default`]: a fixed [`Value`] would
/// be the wrong type for every resolution but one, but a scalar to spread is
/// well defined at all of them.
fn generic_splat(name: &str, default: f32) -> Socket {
    generic_socket(name).with_splat_default(default)
}

/// An expression that falls back to `fallback` where `span` is degenerate.
///
/// The component-wise replacement for `if abs(span) < 1e-8 { return … }`,
/// which only type-checks for `f32`: a vector comparison yields a
/// `vec<bool>`, and `if` demands a scalar. `select(false, true, cond)` takes
/// a vector condition and chooses per component.
///
/// `{$T}` is the resolved WGSL spelling of the node's generic parameter `T`
/// (see [`wxsl_core::codegen`]), which is what lets one template serve every
/// type `T` allows instead of one node per type.
fn guarded(fallback: &str, value: &str, span: &str) -> String {
    format!("select({fallback}, {value}, abs({span}) >= {{$T}}(1e-8))")
}

// ---------------------------------------------------------------------------
// Operators
// ---------------------------------------------------------------------------

/// A unary operator family: one generic node, covering every type its
/// parameter allows.
struct Unary {
    /// Id stem: `math.{stem}` is the node this family becomes.
    stem: &'static str,
    /// Editor label.
    label: &'static str,
    /// Description.
    doc: &'static str,
    /// Expression template over the family's socket names.
    expr: &'static str,
}

/// A binary operator family: one generic node, covering every combination of
/// types WGSL accepts for it.
struct Binary {
    /// Id stem: `math.{stem}`.
    stem: &'static str,
    /// Editor label.
    label: &'static str,
    /// Description.
    doc: &'static str,
    /// Expression template over `a` and `b`.
    expr: &'static str,
    /// How the two operands' types relate.
    ///
    /// `None` — one shared parameter `T` on both operands and the result,
    /// because the WGSL *builtin* behind this family (`pow`, `min`, `max`)
    /// has a single `(T, T) -> T` overload and accepts nothing else.
    ///
    /// `Some(rule)` — two independent parameters `A` and `B` with the
    /// result derived by `rule`, because the WGSL *operator* behind it also
    /// spreads a scalar over a vector's components (`f32 + vec3f` is
    /// `vec3f`), and `*` additionally does linear algebra (`mat3x3f *
    /// vec3f` is `vec3f`). Two parameters is the only way to say "these two
    /// may legitimately differ"; see [`wxsl_core::node::Socket::combine`].
    rule: Option<TypeRule>,
    /// Whether the operands may also be matrices. WGSL adds and subtracts
    /// two matrices of the same shape and multiplies a matrix by a scalar,
    /// a vector or another matrix — but `/` and `%` accept no matrix at
    /// all, and neither does any of the builtins.
    matrices: bool,
}

const BINARY: &[Binary] = &[
    Binary {
        stem: "add",
        label: "Add",
        doc: "Sum of two operands. Either may be a scalar spread over the \
              other's components, and two matrices of the same shape add \
              element-wise.",
        expr: "{a} + {b}",
        rule: Some(TypeRule::Componentwise),
        matrices: true,
    },
    Binary {
        stem: "subtract",
        label: "Subtract",
        doc: "Difference of two operands, with the same mixing rules as \
              `math.add`.",
        expr: "{a} - {b}",
        rule: Some(TypeRule::Componentwise),
        matrices: true,
    },
    Binary {
        stem: "multiply",
        label: "Multiply",
        doc: "Product of two operands. Either may be a scalar spread over \
              the other's components, and a matrix may multiply a vector of \
              its own size — which is how a basis from \
              `space.tangent_basis` is applied to a direction — or another \
              matrix of the same shape.",
        expr: "{a} * {b}",
        rule: Some(TypeRule::Product),
        matrices: true,
    },
    Binary {
        stem: "divide",
        label: "Divide",
        doc: "Quotient of two operands, either of which may be a scalar \
              spread over the other's components. Division by zero yields \
              an infinity, which will spread; guard the divisor if it can \
              reach zero.",
        expr: "{a} / {b}",
        rule: Some(TypeRule::Componentwise),
        matrices: false,
    },
    Binary {
        stem: "modulo",
        label: "Modulo",
        doc: "Floating-point remainder, keeping the sign of the dividend. \
              For a periodic wrap use `math.wrap` instead.",
        expr: "{a} % {b}",
        rule: Some(TypeRule::Componentwise),
        matrices: false,
    },
    Binary {
        stem: "power",
        label: "Power",
        doc: "`a` raised to `b`, component-wise. Undefined for a negative \
              base with a fractional exponent.",
        expr: "pow({a}, {b})",
        rule: None,
        matrices: false,
    },
    Binary {
        stem: "minimum",
        label: "Minimum",
        doc: "Component-wise smaller of the two.",
        expr: "min({a}, {b})",
        rule: None,
        matrices: false,
    },
    Binary {
        stem: "maximum",
        label: "Maximum",
        doc: "Component-wise larger of the two.",
        expr: "max({a}, {b})",
        rule: None,
        matrices: false,
    },
];

const UNARY: &[Unary] = &[
    Unary {
        stem: "negate",
        label: "Negate",
        doc: "Flip the sign, component-wise.",
        expr: "-{a}",
    },
    Unary {
        stem: "absolute",
        label: "Absolute",
        doc: "Drop the sign, component-wise.",
        expr: "abs({a})",
    },
    Unary {
        stem: "sign",
        label: "Sign",
        doc: "-1, 0 or 1 per component.",
        expr: "sign({a})",
    },
    Unary {
        stem: "floor",
        label: "Floor",
        doc: "Round down, component-wise.",
        expr: "floor({a})",
    },
    Unary {
        stem: "ceil",
        label: "Ceil",
        doc: "Round up, component-wise.",
        expr: "ceil({a})",
    },
    Unary {
        stem: "round",
        label: "Round",
        doc: "Round to nearest, halves to even.",
        expr: "round({a})",
    },
    Unary {
        stem: "truncate",
        label: "Truncate",
        doc: "Drop the fractional part, towards zero.",
        expr: "trunc({a})",
    },
    Unary {
        stem: "fraction",
        label: "Fraction",
        doc: "The fractional part, always in [0, 1).",
        expr: "fract({a})",
    },
    Unary {
        stem: "saturate",
        label: "Saturate",
        doc: "Clamp to [0, 1], component-wise.",
        expr: "saturate({a})",
    },
    Unary {
        stem: "square_root",
        label: "Square root",
        doc: "Component-wise square root; negative inputs give NaN.",
        expr: "sqrt({a})",
    },
    Unary {
        stem: "inverse_square_root",
        label: "Inverse square root",
        doc: "1/sqrt, component-wise, as a single instruction.",
        expr: "inverseSqrt({a})",
    },
    Unary {
        stem: "exponential",
        label: "Exponential",
        doc: "e raised to the input, component-wise.",
        expr: "exp({a})",
    },
    Unary {
        stem: "exponential_2",
        label: "Exponential (base 2)",
        doc: "2 raised to the input, component-wise.",
        expr: "exp2({a})",
    },
    Unary {
        stem: "logarithm",
        label: "Logarithm",
        doc: "Natural log, component-wise.",
        expr: "log({a})",
    },
    Unary {
        stem: "logarithm_2",
        label: "Logarithm (base 2)",
        doc: "Base-2 log, component-wise.",
        expr: "log2({a})",
    },
    Unary {
        stem: "sine",
        label: "Sine",
        doc: "Sine of an angle in radians.",
        expr: "sin({a})",
    },
    Unary {
        stem: "cosine",
        label: "Cosine",
        doc: "Cosine of an angle in radians.",
        expr: "cos({a})",
    },
    Unary {
        stem: "tangent",
        label: "Tangent",
        doc: "Tangent of an angle in radians.",
        expr: "tan({a})",
    },
    Unary {
        stem: "arcsine",
        label: "Arcsine",
        doc: "Inverse sine, in radians. Input outside [-1, 1] gives NaN.",
        expr: "asin({a})",
    },
    Unary {
        stem: "arccosine",
        label: "Arccosine",
        doc: "Inverse cosine, in radians. Input outside [-1, 1] gives NaN.",
        expr: "acos({a})",
    },
    Unary {
        stem: "arctangent",
        label: "Arctangent",
        doc: "Inverse tangent, in radians.",
        expr: "atan({a})",
    },
];

/// Arithmetic and the WGSL builtins that go with it, one generic node per
/// family instead of one per family *and* type.
///
/// `{a} + {b}` is the same WXSL whatever the operands are, so what used to
/// differ between `math.add.f32`, `math.add.vec2f`, `math.add.vec3f` and
/// `math.add.vec4f` was only the type annotation on otherwise identical
/// sockets ([ADR 0015](../../../docs/adr/0015-generic-sockets-for-arithmetic-nodes.md)).
/// The families whose operands WGSL lets differ declare two parameters and
/// derive the result, rather than forcing one shared `T` on both — see
/// [`Binary::rule`] and
/// [ADR 0018](../../../docs/adr/0018-one-generic-node-per-operation.md).
pub fn math_nodes() -> Vec<NodeDefinition> {
    let mut defs = Vec::new();
    for family in BINARY {
        let allowed = if family.matrices {
            ValueType::operands()
        } else {
            ValueType::FLOATS.to_vec()
        };
        let builder = NodeDefinition::builder(format!("math.{}", family.stem), family.label)
            .category("math")
            .doc(family.doc);
        defs.push(match family.rule {
            None => builder
                .generic_param(param("T", &allowed))
                .input(generic_socket("a"))
                .input(generic_socket("b"))
                .output(generic_socket("out"))
                .expr(family.expr),
            Some(rule) => builder
                .generic_param(param("A", &allowed))
                .generic_param(param("B", &allowed))
                .input(Socket::new("a", ValueType::F32).generic("A"))
                .input(Socket::new("b", ValueType::F32).generic("B"))
                .output(Socket::new("out", ValueType::F32).combine(rule, "A", "B"))
                .expr(family.expr),
        });
    }
    for family in UNARY {
        defs.push(
            NodeDefinition::builder(format!("math.{}", family.stem), family.label)
                .category("math")
                .doc(family.doc)
                .generic_param(shared(ValueType::FLOATS))
                .input(generic_socket("a"))
                .output(generic_socket("out"))
                .expr(family.expr),
        );
    }

    // Operators whose sockets are not interchangeable operands, so they are
    // spelled out rather than generated from a table. They are still one
    // generic node each: every socket below either carries `T` or is a
    // scalar that WGSL accepts at *every* type `T` allows, which is a fixed
    // type rather than a per-type split.
    defs.push(
        NodeDefinition::builder("math.clamp", "Clamp")
            .category("math")
            .doc("Constrain to a range, component-wise.")
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("x", 0.0))
            .input(generic_splat("low", 0.0))
            .input(generic_splat("high", 1.0))
            .output(generic_socket("out"))
            .expr("clamp({x}, {low}, {high})"),
    );
    defs.push(
        NodeDefinition::builder("math.mix", "Mix")
            .category("math")
            .doc(
                "Linear blend: `a` at t=0, `b` at t=1, extrapolating \
                 outside. `t` is a scalar, which WGSL's `mix` accepts \
                 against operands of any width.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("a", 0.0))
            .input(generic_splat("b", 1.0))
            .input(scalar("t", 0.5))
            .output(generic_socket("out"))
            .expr("mix({a}, {b}, {t})"),
    );
    defs.push(
        NodeDefinition::builder("math.step", "Step")
            .category("math")
            .doc("0 below the edge, 1 at or above it, component-wise.")
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("edge", 0.5))
            .input(generic_splat("x", 0.0))
            .output(generic_socket("out"))
            .expr("step({edge}, {x})"),
    );
    defs.push(
        NodeDefinition::builder("math.smoothstep", "Smoothstep")
            .category("math")
            .doc(
                "Hermite ramp between two edges. For a continuous second \
                 derivative use `math.smootherstep`.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("edge0", 0.0))
            .input(generic_splat("edge1", 1.0))
            .input(generic_splat("x", 0.5))
            .output(generic_socket("out"))
            .expr("smoothstep({edge0}, {edge1}, {x})"),
    );

    // Range operators. These have a body in the mathematical sense — a
    // span, and a guard for the degenerate case where it is zero — but they
    // stay expressions rather than WXSL functions so that one template
    // covers every type `T` allows. A scalar `if` cannot: for the vector
    // types `abs(span) < 1e-8` is a `vec<bool>`, which `if` rejects.
    // `guarded` reshapes it into a `select`, which also gives the better
    // semantics — one degenerate component collapses only itself, not the
    // whole vector. The span appears more than once in the emitted
    // expression; the shader compiler folds it.
    defs.push(
        NodeDefinition::builder("math.inverse_lerp", "Inverse lerp")
            .category("math")
            .doc(
                "Where a value sits between two others, as a 0..1 factor — \
                 the inverse of `math.mix`. Components where `a == b` give 0.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("a", 0.0))
            .input(generic_splat("b", 1.0))
            .input(generic_splat("value", 0.5))
            .output(generic_socket("out"))
            .expr(guarded(
                "{$T}(0.0)",
                "({value} - {a}) / ({b} - {a})",
                "({b} - {a})",
            )),
    );
    defs.push(
        NodeDefinition::builder("math.remap", "Remap")
            .category("math")
            .doc(
                "Map a value from [in_min, in_max] onto [out_min, out_max]. \
                 Not clamped: feed the result through `math.clamp` if the \
                 input can leave its stated range. A zero-width input range \
                 gives `out_min`.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("value", 0.0))
            .input(generic_splat("in_min", 0.0))
            .input(generic_splat("in_max", 1.0))
            .input(generic_splat("out_min", 0.0))
            .input(generic_splat("out_max", 1.0))
            .output(generic_socket("out"))
            .expr(guarded(
                "{out_min}",
                "{out_min} + ({value} - {in_min}) * ({out_max} - {out_min}) \
                 / ({in_max} - {in_min})",
                "({in_max} - {in_min})",
            )),
    );
    defs.push(
        NodeDefinition::builder("math.wrap", "Wrap")
            .category("math")
            .doc(
                "Wrap a value into [low, high), the way a repeating texture \
                 coordinate does. Unlike `math.modulo` this is correct for \
                 negative inputs: wrapping -0.25 into 0..1 gives 0.75.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("value", 0.0))
            .input(generic_splat("low", 0.0))
            .input(generic_splat("high", 1.0))
            .output(generic_socket("out"))
            .expr(guarded(
                "{low}",
                "{low} + ({high} - {low}) \
                 * fract(({value} - {low}) / ({high} - {low}))",
                "({high} - {low})",
            )),
    );

    defs.push(
        NodeDefinition::builder("math.arctangent2", "Arctangent 2")
            .category("math")
            .doc(
                "Angle of the vector (x, y) in radians, over the full \
                 circle. Component-wise for the vector types, which makes \
                 it a field of angles rather than one angle.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("y", 0.0))
            .input(generic_splat("x", 1.0))
            .output(generic_socket("out"))
            .expr("atan2({y}, {x})"),
    );
    defs
}

/// Vector algebra: the operations that change or collapse dimensionality.
///
/// One generic node each, over the *vector* types — `dot`, `normalize`,
/// `reflect` and `refract` need more than one component to mean anything,
/// so their parameter allows `vec2f | vec3f | vec4f` rather than
/// [`ValueType::FLOATS`]. The reductions (`dot`, `length`, `distance`)
/// output a fixed `f32` however wide the input is, which is a concrete type
/// and not a per-type split.
pub fn vector_nodes() -> Vec<NodeDefinition> {
    vec![
        NodeDefinition::builder("vector.dot", "Dot product")
            .category("vector")
            .doc(
                "Sum of component-wise products; the cosine of the angle \
                 between two unit vectors.",
            )
            .generic_param(shared(ValueType::VECTORS))
            .input(generic_splat("a", 0.0))
            .input(generic_splat("b", 0.0))
            .output(out(ValueType::F32))
            .expr("dot({a}, {b})"),
        NodeDefinition::builder("vector.length", "Length")
            .category("vector")
            .doc("Euclidean length.")
            .generic_param(shared(ValueType::VECTORS))
            .input(generic_splat("v", 0.0))
            .output(out(ValueType::F32))
            .expr("length({v})"),
        NodeDefinition::builder("vector.distance", "Distance")
            .category("vector")
            .doc("Euclidean distance between two points.")
            .generic_param(shared(ValueType::VECTORS))
            .input(generic_splat("a", 0.0))
            .input(generic_splat("b", 0.0))
            .output(out(ValueType::F32))
            .expr("distance({a}, {b})"),
        NodeDefinition::builder("vector.normalize", "Normalize")
            .category("vector")
            .doc(
                "Scale to unit length. A zero-length input gives NaN; use \
                 `math.safe_normalize` where that is possible.",
            )
            .generic_param(shared(ValueType::VECTORS))
            .input(generic_splat("v", 0.0))
            .output(generic_socket("out"))
            .expr("normalize({v})"),
        NodeDefinition::builder("vector.reflect", "Reflect")
            .category("vector")
            .doc(
                "Mirror an incident direction about a normal. Both should be \
                 unit length, and `incident` points *at* the surface.",
            )
            .generic_param(shared(ValueType::VECTORS))
            .input(generic_splat("incident", 0.0))
            .input(generic_splat("normal", 0.0))
            .output(generic_socket("out"))
            .expr("reflect({incident}, {normal})"),
        NodeDefinition::builder("vector.refract", "Refract")
            .category("vector")
            .doc(
                "Bend an incident direction through a surface. `eta` is the \
                 ratio of refractive indices; total internal reflection \
                 returns the zero vector.",
            )
            .generic_param(shared(ValueType::VECTORS))
            .input(generic_splat("incident", 0.0))
            .input(generic_splat("normal", 0.0))
            .input(scalar("eta", 1.0 / 1.5))
            .output(generic_socket("out"))
            .expr("refract({incident}, {normal}, {eta})"),
        NodeDefinition::builder("vector.transform", "Transform by matrix")
            .category("vector")
            .doc(
                "Multiply a vector by a matrix of its own size — the way to \
                 use a basis from `space.tangent_basis`, or any other \
                 frame, on a direction. `M` and `V` resolve independently, \
                 so a mat3x3f with a vec4f is reported rather than \
                 silently accepted.",
            )
            .generic_param(param("M", ValueType::MATRICES))
            // Not every vector: `Product` never combines a matrix with a
            // `vec2f`, so offering one would be offering a type that can
            // never resolve — and `V`'s first allowed type is what a freshly
            // placed node starts at, which has to combine with `M`'s.
            .generic_param(param("V", &[ValueType::Vec3, ValueType::Vec4]))
            .input(
                Socket::new("m", ValueType::Mat3)
                    .generic("M")
                    .with_splat_default(1.0),
            )
            .input(
                Socket::new("v", ValueType::Vec3)
                    .generic("V")
                    .with_splat_default(1.0),
            )
            .output(Socket::new("out", ValueType::Vec3).combine(TypeRule::Product, "M", "V"))
            .expr("{m} * {v}"),
        // `cross` is the one vector operation WGSL defines for exactly one
        // width, so this is a concrete node rather than a generic one with
        // a single allowed type.
        NodeDefinition::builder("vector.cross", "Cross product")
            .category("vector")
            .doc("The vector perpendicular to both inputs, right-handed.")
            .input(direction("a", [1.0, 0.0, 0.0]))
            .input(direction("b", [0.0, 1.0, 0.0]))
            .output(out(ValueType::Vec3))
            .expr("cross({a}, {b})"),
    ]
}

/// Conversions between scalars and vectors: splat, combine, split.
///
/// Sockets are matched by exact type, so these are how a graph changes
/// dimensionality — no implicit promotion happens behind the author's back.
///
/// `convert.combine` and `convert.split` are the two families in this
/// library that stay one node *per* type: how many sockets they have is
/// part of what the type is (a `vec4f` split has four outputs, a `vec2f`
/// split has two), and a [`GenericParam`] resolves a socket's type, not a
/// node's socket list. `convert.splat` has the same one input and one
/// output at every width, so it is generic like everything else — with
/// `{$T}` naming the resolved type in the constructor it emits.
pub fn convert_nodes() -> Vec<NodeDefinition> {
    let component_names = ["x", "y", "z", "w"];
    let mut defs = Vec::new();

    defs.push(
        // The only node that consumes an integer or a boolean and
        // produces a number, and therefore the only way one reaches the
        // surface at all. It earns its place now that `param.value` can
        // be an `i32` count or a `bool` toggle the host flips without a
        // recompile: without it those are values with nowhere to go.
        NodeDefinition::builder("convert.to_float", "To float")
            .doc(
                "Convert a boolean or an integer to `f32`. `false` is 0 \
                 and `true` is 1.",
            )
            .generic_param(param(
                "T",
                &[ValueType::Bool, ValueType::I32, ValueType::U32],
            ))
            .input(generic_socket("value").with_doc("The value to convert."))
            .output(out(ValueType::F32))
            .expr("f32({value})"),
    );
    defs.push(
        NodeDefinition::builder("convert.splat", "Splat")
            .category("convert")
            .doc("Copy one scalar into every component.")
            .generic_param(shared(ValueType::VECTORS))
            .input(scalar("value", 0.0))
            .output(generic_socket("out"))
            .expr("{$T}({value})"),
    );

    for ty in [ValueType::Vec2, ValueType::Vec3, ValueType::Vec4] {
        let count = ty.component_count().expect("float vector") as usize;

        let mut combine =
            NodeDefinition::builder(format!("convert.combine.{}", ty.suffix()), "Combine")
                .category("convert")
                .doc("Build a vector from its components.");
        let mut expr = format!("{}(", ty.wxsl_type());
        for (index, name) in component_names[..count].iter().enumerate() {
            // Alpha defaults to 1, so a colour built without it is opaque.
            let default = if ty == ValueType::Vec4 && index == 3 {
                1.0
            } else {
                0.0
            };
            combine = combine.input(scalar(name, default));
            if index > 0 {
                expr.push_str(", ");
            }
            expr.push('{');
            expr.push_str(name);
            expr.push('}');
        }
        expr.push(')');
        defs.push(combine.output(out(ty)).expr(expr));

        let mut split = NodeDefinition::builder(format!("convert.split.{}", ty.suffix()), "Split")
            .category("convert")
            .doc("Take a vector apart into its components.")
            .input(splat("v", ty, 0.0));
        let mut exprs = Vec::with_capacity(count);
        for name in &component_names[..count] {
            split = split.output(Socket::new(name, ValueType::F32));
            exprs.push(format!("{{v}}.{name}"));
        }
        defs.push(split.exprs(exprs));
    }
    defs
}

/// Comparison and boolean logic, plus the `select` that makes a `bool`
/// useful in a graph without branching.
pub fn logic_nodes() -> Vec<NodeDefinition> {
    let comparisons: &[(&str, &str, &str)] = &[
        ("less", "Less than", "{a} < {b}"),
        ("less_equal", "Less or equal", "{a} <= {b}"),
        ("greater", "Greater than", "{a} > {b}"),
        ("greater_equal", "Greater or equal", "{a} >= {b}"),
        ("equal", "Equal", "{a} == {b}"),
        ("not_equal", "Not equal", "{a} != {b}"),
    ];
    let mut defs = Vec::new();
    for (stem, label, expr) in comparisons {
        defs.push(
            // Scalar-only, and honestly so rather than as a family with
            // one member: WGSL's comparison operators on vectors give a
            // `vecN<bool>`, which `ValueType` does not carry, so there is
            // no type for a generic output to resolve to.
            NodeDefinition::builder(format!("compare.{stem}"), *label)
                .category("compare")
                .doc(
                    "Compare two scalars. Exact float comparison is rarely \
                      what you want for equality; compare a difference \
                      against a tolerance instead.",
                )
                .input(scalar("a", 0.0))
                .input(scalar("b", 0.0))
                .output(out(ValueType::Bool))
                .expr(*expr),
        );
    }

    let boolean =
        |name: &str, label: &'static str, doc: &'static str, expr: &'static str, binary: bool| {
            let mut builder = NodeDefinition::builder(format!("logic.{name}"), label)
                .category("logic")
                .doc(doc)
                .input(Socket::new("a", ValueType::Bool).with_default(Value::Bool(false)));
            if binary {
                builder = builder
                    .input(Socket::new("b", ValueType::Bool).with_default(Value::Bool(false)));
            }
            builder.output(out(ValueType::Bool)).expr(expr)
        };
    defs.push(boolean(
        "and",
        "And",
        "True when both inputs are true.",
        "{a} && {b}",
        true,
    ));
    defs.push(boolean(
        "or",
        "Or",
        "True when either input is true.",
        "{a} || {b}",
        true,
    ));
    defs.push(boolean("not", "Not", "Invert a boolean.", "!{a}", false));

    defs.push(
        NodeDefinition::builder("logic.select", "Select")
            .category("logic")
            .doc(
                "Pick one of two values by a condition. Both inputs are \
                 evaluated — this is a data selection, not a branch.",
            )
            .generic_param(shared(ValueType::FLOATS))
            .input(generic_splat("if_false", 0.0))
            .input(generic_splat("if_true", 1.0))
            .input(Socket::new("condition", ValueType::Bool).with_default(Value::Bool(false)))
            .output(generic_socket("out"))
            .expr("select({if_false}, {if_true}, {condition})"),
    );
    defs
}

/// Literal values: one generic node, plus `bool`.
///
/// A constant node earns its place over typing the value into the consuming
/// socket when several sockets should share one value: change it once and
/// every consumer follows.
pub fn constant_nodes() -> Vec<NodeDefinition> {
    vec![
        NodeDefinition::builder("const.value", "Constant")
            .category("const")
            .doc(
                "A literal value, shared by everything wired to it. A \
                 matrix constant defaults to the identity, which is the \
                 diagonal a splat default builds.",
            )
            .generic_param(shared(&ValueType::operands()))
            .input(generic_splat("value", 1.0))
            .output(generic_socket("out"))
            .expr("{value}"),
        // `bool` has no float components, so it is not one of `T`'s allowed
        // types and cannot share the node above; a splat default has
        // nothing to build there either.
        NodeDefinition::builder("const.bool", "Constant (boolean)")
            .category("const")
            .doc("A literal boolean.")
            .input(Socket::new("value", ValueType::Bool).with_default(Value::Bool(false)))
            .output(out(ValueType::Bool))
            .expr("{value}"),
    ]
}

/// Every type a host-shared value can have, ordered for a "pick a type"
/// control on a parameter.
///
/// [`ValueType::ALL`]'s own order starts at `bool`, and the first allowed
/// type is what a freshly placed node resolves to
/// ([`NodeDefinition::default_generics`]) — so a parameter dropped on the
/// canvas would be a boolean, which is not what anybody reaches for a
/// parameter to be. The arithmetic types come first here and the rest
/// follow; the *set* is the same.
fn parameter_types() -> Vec<ValueType> {
    let mut types = ValueType::operands();
    types.extend([ValueType::Bool, ValueType::I32, ValueType::U32]);
    types
}

/// What a material declares it needs from outside itself: uniform
/// parameters, textures, samplers, and the application's own block.
///
/// The counterpart to [`constant_nodes`], and the difference is the whole
/// point. A `const` is inlined into the generated WXSL, so editing one
/// compiles a new shader variant; a `param` is a field of the material's
/// uniform buffer, so editing one writes four bytes and the frame after it
/// draws the same pipeline. A slider that does not recompile is what this
/// buys ([ADR 0023](../../../docs/adr/0023-a-material-declares-its-resources.md)).
///
/// Each of these carries a **setting** — a string the node instance holds —
/// naming the thing it declares. Two nodes naming the same parameter *are*
/// the same parameter, which is how one slider drives two places without a
/// wire crossing the canvas.
pub fn declaration_nodes() -> Vec<NodeDefinition> {
    let named = |doc: &str, default: &str| {
        SettingDef::new(node::SETTING_NAME, "name", doc).with_default(default)
    };
    vec![
        NodeDefinition::builder("param.value", "Parameter")
            .category("param")
            .doc(
                "A value the host can change without recompiling: a field \
                 of this material's uniform buffer. Unlike a constant, \
                 editing it costs a buffer write rather than a new shader \
                 variant. The `value` socket is its starting value, and \
                 two parameters with the same name are one parameter.",
            )
            .setting(named(
                "The name the host writes this parameter by, and the field \
                 name in the generated struct.",
                "amount",
            ))
            // Every type, not just the arithmetic ones: an `i32` count or a
            // `bool` toggle is exactly the sort of knob that should not
            // cost a recompile, and `ValueType::splat` gives all of them a
            // default to start from.
            .generic_param(param("T", &parameter_types()))
            .input(generic_splat("value", 0.0).constant())
            .output(generic_socket("out"))
            .declaration(NodeBody::Param),
        NodeDefinition::builder("texture.texture_2d", "Texture 2D")
            .category("texture")
            .doc(
                "A 2D texture the application binds by name. Wire it into \
                 a sampling node together with a sampler.",
            )
            .setting(named(
                "The name the application binds this texture by.",
                "albedo",
            ))
            .output(out(ValueType::Texture2d))
            .declaration(NodeBody::Resource),
        NodeDefinition::builder("texture.texture_cube", "Texture cube")
            .category("texture")
            .doc("A cube texture the application binds by name.")
            .setting(named(
                "The name the application binds this texture by.",
                "environment",
            ))
            .output(out(ValueType::TextureCube))
            .declaration(NodeBody::Resource),
        NodeDefinition::builder("texture.sampler", "Sampler")
            .category("texture")
            .doc(
                "How a texture is filtered and wrapped, bound by the \
                 application. One sampler serves every texture read \
                 through it.",
            )
            .setting(named(
                "The name the application binds this sampler by.",
                "linear",
            ))
            .output(out(ValueType::Sampler))
            .declaration(NodeBody::Resource),
        NodeDefinition::builder("input.user", "Application value")
            .category("input")
            .doc(
                "One field of the uniform block this graph expects the \
                 application to supply. The graph declares the block's \
                 fields; wxsl never knows what is in it, only its shape.",
            )
            .setting(
                SettingDef::new(
                    node::SETTING_FIELD,
                    "field",
                    "Which field of the application block to read.",
                )
                .with_default("value"),
            )
            .generic_param(param("T", &parameter_types()))
            .output(generic_socket("out"))
            .declaration(NodeBody::UserRead),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shaders;
    use wxsl_core::graph::{Graph, Node, UserBlockDecl, UserField};
    use wxsl_core::node::NodeBody;

    #[test]
    fn registry_has_no_duplicate_ids() {
        // `register_all` panics on a duplicate, so building it is the test.
        let registry = registry();
        assert_eq!(registry.len(), all_nodes().len());
    }

    #[test]
    fn every_operator_family_is_exactly_one_node_covering_every_type_it_allows() {
        // One registry entry per family — not one per family *and* type,
        // which is the duplication generic sockets exist to remove — and
        // every socket's type governed by a parameter rather than fixed.
        let registry = registry();
        for (id, params, allowed) in BINARY
            .iter()
            .map(|family| {
                let params: &[&str] = match family.rule {
                    None => &["T"],
                    Some(_) => &["A", "B"],
                };
                let allowed = if family.matrices {
                    ValueType::operands()
                } else {
                    ValueType::FLOATS.to_vec()
                };
                (format!("math.{}", family.stem), params, allowed)
            })
            .chain(UNARY.iter().map(|family| {
                (
                    format!("math.{}", family.stem),
                    &["T"][..],
                    ValueType::FLOATS.to_vec(),
                )
            }))
        {
            let def = registry
                .get(&id)
                .unwrap_or_else(|| panic!("missing `{id}`"));
            for suffix in ValueType::FLOATS {
                assert!(
                    !registry.contains(&format!("{id}.{}", suffix.suffix())),
                    "`{id}.{suffix}` should not exist alongside the generic `{id}`"
                );
            }
            assert_eq!(
                def.generics
                    .iter()
                    .map(|param| param.name.as_str())
                    .collect::<Vec<_>>(),
                params,
                "`{id}` declares the wrong type parameters"
            );
            for param in &def.generics {
                assert_eq!(
                    param.allowed, allowed,
                    "`{id}`'s `{}` allows the wrong types",
                    param.name
                );
            }
            for socket in def.inputs.iter().chain(&def.outputs) {
                assert!(
                    socket.referenced_params().next().is_some(),
                    "`{id}`'s socket `{}` has a fixed type, not a parameter",
                    socket.name
                );
                assert!(
                    socket.default.is_none(),
                    "`{id}`'s socket `{}` is generic and must have no fixed default",
                    socket.name
                );
            }
        }
    }

    #[test]
    fn the_operators_whose_operands_may_differ_declare_two_parameters() {
        // `+`, `-`, `*`, `/` and `%` all spread a scalar over a vector, so
        // their two operands resolve independently and the result is
        // derived from both. `pow`/`min`/`max` are builtins with a single
        // `(T, T) -> T` overload, so they share one parameter.
        let registry = registry();
        let rule_of = |id: &str| {
            registry
                .get(id)
                .unwrap_or_else(|| panic!("missing `{id}`"))
                .output("out")
                .expect("has an `out` output")
                .combine
                .as_ref()
                .map(|combined| {
                    (
                        combined.rule,
                        combined.a.to_string(),
                        combined.b.to_string(),
                    )
                })
        };
        for id in ["math.add", "math.subtract", "math.divide", "math.modulo"] {
            assert_eq!(
                rule_of(id),
                Some((TypeRule::Componentwise, "A".into(), "B".into())),
                "`{id}`'s output should combine `A` and `B` componentwise"
            );
        }
        assert_eq!(
            rule_of("math.multiply"),
            Some((TypeRule::Product, "A".into(), "B".into())),
            "`*` also does linear algebra, which `Componentwise` does not cover"
        );
        for id in ["math.power", "math.minimum", "math.maximum"] {
            assert_eq!(rule_of(id), None, "`{id}` shares one parameter");
        }

        // Matrices are operands of `+`, `-` and `*` and of nothing else.
        for id in ["math.add", "math.subtract", "math.multiply"] {
            let def = registry.get(id).unwrap();
            assert!(def
                .generics
                .iter()
                .all(|param| param.allowed.contains(&ValueType::Mat3)));
        }
        for id in ["math.divide", "math.modulo", "math.power", "math.negate"] {
            let def = registry.get(id).unwrap();
            assert!(
                def.generics
                    .iter()
                    .all(|param| !param.allowed.contains(&ValueType::Mat3)),
                "`{id}` takes no matrix in WGSL"
            );
        }
    }

    #[test]
    fn no_definition_id_carries_a_type_suffix_a_parameter_could_replace() {
        // Two exceptions. `convert.combine`/`convert.split` have a socket
        // *count* that is part of the type, so one node cannot serve every
        // width. `const.bool` names a type that is not in any parameter's
        // allowed set — `bool` is not a float, and a splat default has
        // nothing to spread there. Everything else that was once a per-type
        // family is one node now.
        let allowed_per_type = ["convert.combine.", "convert.split.", "const.bool"];
        for def in all_nodes() {
            let suffixed = ValueType::ALL
                .iter()
                .any(|ty| def.id.ends_with(&format!(".{}", ty.suffix())));
            assert!(
                !suffixed || allowed_per_type.iter().any(|stem| def.id.starts_with(stem)),
                "`{}` still names a type in its id",
                def.id
            );
        }
    }

    #[test]
    fn a_splat_default_on_a_generic_socket_follows_the_resolved_type() {
        // `clamp`'s `high` is 1 at every width: one scalar on the
        // definition, spread over whatever the instance resolved to.
        let registry = registry();
        let high = registry
            .get("math.clamp")
            .expect("registered")
            .input("high")
            .expect("has a `high` input");
        assert_eq!(high.default, None, "no fixed default on a generic socket");
        assert_eq!(high.splat_default, Some(1.0));
        assert_eq!(high.default_for(ValueType::F32), Some(Value::F32(1.0)));
        assert_eq!(
            high.default_for(ValueType::Vec3),
            Some(Value::Vec3([1.0; 3]))
        );
        assert!(!high.is_required(), "a splat default feeds the socket");
    }

    #[test]
    fn every_definition_is_valid_at_its_default_types() {
        // `NodeDefinition::default_generics` is what a node placed on a
        // canvas starts at, so those types have to actually work together:
        // `vector.transform` starting at `mat3x3f` with a `vec2f` would be
        // a node that reports `IncompatibleGenerics` before anyone touched
        // it. This is the constraint on the *order* of every
        // `GenericParam::allowed` in this file.
        let registry = registry();
        let mut graph = Graph::new("defaults");
        // `input.user` reads a block the *document* declares, so a graph
        // that holds one has to declare one. Its default field, at its
        // default type.
        graph.set_user_block(UserBlockDecl {
            name: "app".to_string(),
            fields: vec![UserField::new("value", ValueType::F32)],
        });
        let mut resource_inputs = 0;
        for def in registry.iter() {
            if def.is_surface_output() {
                continue;
            }
            let node = graph.add_resolved(&registry, Node::new(def.id.clone()));
            for socket in def.inputs.iter().chain(&def.outputs) {
                assert!(
                    graph.effective_type(node, socket).is_some(),
                    "`{}`'s socket `{}` has no type at the default {:?}",
                    def.id,
                    socket.name,
                    def.default_generics()
                );
            }
            resource_inputs += def
                .inputs
                .iter()
                .filter(|socket| socket.ty.is_resource())
                .count();
        }
        // Every one of them is complete on its own: no unresolved
        // parameter, nothing to report — except that a texture or sampler
        // input has no default and cannot have one. There is no literal
        // texture to type in, so "connect something" is the only way to
        // feed it, and `MissingInput` saying so is correct rather than a
        // gap in the defaults.
        let errors = match graph.validate(&registry) {
            Ok(()) => Vec::new(),
            Err(errors) => errors.0,
        };
        assert!(resource_inputs > 0, "no resource sockets left to except");
        assert_eq!(
            errors.len(),
            resource_inputs,
            "a freshly placed node of every kind is valid apart from its \
             resource inputs: {errors:?}"
        );
        for error in &errors {
            assert!(
                matches!(error, wxsl_core::GraphError::MissingInput { .. }),
                "{error:?}"
            );
        }
    }

    /// Every function node came from a `.wxsl` file, so this is the set
    /// `derived_nodes` should be exactly.
    fn node_source_modules() -> Vec<&'static str> {
        shaders::MODULES
            .iter()
            .map(|(path, _)| *path)
            .filter(|path| !path.starts_with("package::wxsl::"))
            .collect()
    }

    #[test]
    fn every_function_node_is_derived_from_a_shader_this_crate_ships() {
        // The predecessor of this test checked that a hand-written
        // descriptor pointed at a module that existed and named a function
        // that existed. That drift is no longer expressible — the descriptor
        // *is* the file — so what is worth checking now is the other
        // direction: that every shipped function file became a node, and
        // that no derived node points anywhere else.
        let derived: Vec<String> = derived_nodes()
            .iter()
            .map(|def| match &def.body {
                NodeBody::Call(func) => func.module.as_str().to_string(),
                other => panic!("`{}` is a {other:?}, not a call", def.id),
            })
            .collect();
        let mut expected: Vec<String> = node_source_modules()
            .iter()
            .map(|path| (*path).to_string())
            .collect();
        expected.sort();
        let mut found = derived.clone();
        found.sort();
        assert_eq!(found, expected);
    }

    #[test]
    fn the_generated_table_is_what_the_derivation_answers_now() {
        // `build.rs` derives each node with `wxsl_lang::node_from_source`
        // and then *serializes* it as Rust source. The serializer is
        // mechanical, but it is still a second piece of code between the
        // shader and the registry, so this re-derives every node from the
        // embedded source at test time and compares. A discrepancy means the
        // serializer dropped something the derivation produced — or that the
        // generated table is stale, which cargo should have prevented.
        let generated = derived_nodes();
        for (path, source) in shaders::MODULES
            .iter()
            .filter(|(path, _)| !path.starts_with("package::wxsl::"))
        {
            let fresh = wxsl_lang::node_from_source(source, path).unwrap_or_else(|errors| {
                panic!(
                    "{path} no longer derives:\n{}",
                    errors.render(&|_| Some((*source).to_string()))
                )
            });
            let baked = generated
                .iter()
                .find(|def| def.id == fresh.id)
                .unwrap_or_else(|| panic!("`{}` is not in the generated table", fresh.id));
            assert_eq!(baked, &fresh, "`{}` was serialized lossily", fresh.id);
        }
    }

    #[test]
    fn socket_defaults_match_socket_types() {
        for def in all_nodes() {
            for socket in def.inputs.iter().chain(&def.outputs) {
                if let Some(default) = socket.default {
                    assert_eq!(
                        default.ty(),
                        socket.ty,
                        "`{}`'s socket `{}` has a {} default",
                        def.id,
                        socket.name,
                        default.ty()
                    );
                }
            }
        }
    }

    #[test]
    fn expression_placeholders_name_real_sockets() {
        for def in all_nodes() {
            let NodeBody::Expr(exprs) = &def.body else {
                continue;
            };
            for expr in exprs {
                let mut rest = expr.as_str();
                while let Some(open) = rest.find('{') {
                    rest = &rest[open + 1..];
                    let close = rest.find('}').expect("closed placeholder");
                    let name = &rest[..close];
                    // `{$T}` names a generic parameter, not a socket; the
                    // node builder already checks those are declared.
                    if let Some(param) = name.strip_prefix('$') {
                        assert!(
                            def.generic(param).is_some(),
                            "`{}` references `{{${param}}}`, which it does not declare",
                            def.id
                        );
                    } else {
                        assert!(
                            def.input(name).is_some(),
                            "`{}` references `{{{name}}}`, which is not an input",
                            def.id
                        );
                    }
                    rest = &rest[close + 1..];
                }
            }
        }
    }
}
