//! Derive this library's function nodes from the `.wxsl` files themselves.
//!
//! A shader function file *is* a node
//! ([ADR 0020](../../docs/adr/0020-a-node-definition-is-derived-from-its-wxsl-source.md)):
//! `wxsl_lang::node_from_source` reads one and answers with the
//! `NodeDefinition` the graph needs, and this script runs it over every file
//! under `shaders/<category>/` and writes the results out as Rust source
//! that `registry.rs` includes.
//!
//! # Why at build time
//!
//! Because the alternative costs a dependency the shipped crate does not
//! want. `wxsl-lang` is a **build**-dependency here, so `cargo tree -e
//! normal` still shows `wxsl-stdlib → wxsl-core` and nothing else: a
//! consumer who only wants the node library does not compile a shader
//! compiler to get it. The derivation itself is the same public function the
//! editor calls at runtime on a file the user just wrote, so there is one
//! implementation of the convention, not two.
//!
//! What this script adds on top is only a *serializer*: `NodeDefinition` out,
//! Rust source in. It knows nothing about the convention — no comment
//! parsing, no defaults, no type mapping — so it cannot drift from the
//! derivation the way a second parser could.
//! `the_generated_table_is_what_the_derivation_answers_now` in `registry.rs`
//! re-derives every node at test time and compares, which is the check that
//! keeps that claim true.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use wxsl_core::macros::{MacroDef, MacroValue};
use wxsl_core::node::{
    FunctionReturn, GenericParam, NodeBody, NodeDefinition, Socket, Value, ValueType,
};

/// The subdirectory of `shaders/` holding the ABI rather than node sources.
///
/// `shaders/wxsl/` is the vocabulary a generated material module is written
/// against: entry points, bindings, several functions per file. None of it is
/// a node, so none of it is derived.
const ABI_DIRECTORY: &str = "wxsl";

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("shaders");
    println!("cargo::rerun-if-changed={}", root.display());

    let mut sources = BTreeMap::new();
    for (module_path, path) in node_sources(&root) {
        println!("cargo::rerun-if-changed={}", path.display());
        let source = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        sources.insert(module_path, (path, source));
    }
    assert!(
        !sources.is_empty(),
        "no node sources found under {}",
        root.display()
    );

    let mut out = String::from(
        "// Generated by build.rs from the `.wxsl` files under `shaders/`.\n\
         // Do not edit: change the shader source instead (ADR 0020).\n\n\
         /// Every node derived from a `.wxsl` file in this crate, by module path.\n\
         ///\n\
         /// Written by `build.rs`, which calls `wxsl_lang::node_from_source` on\n\
         /// each file under `shaders/<category>/`. A signature, a socket default\n\
         /// or a macro declaration is therefore stated once, in the shader.\n\
         pub fn derived_nodes() -> Vec<NodeDefinition> {\n\
         \x20   vec![\n",
    );
    for (module_path, (path, source)) in &sources {
        let definition =
            wxsl_lang::node_from_source(source, module_path).unwrap_or_else(|errors| {
                panic!(
                    "{}:\n{}",
                    path.display(),
                    errors.render(&|_| Some(source.clone()))
                )
            });
        let _ = writeln!(out, "        {},", definition_expr(&definition));
    }
    out.push_str("    ]\n}\n");

    let destination = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("derived_nodes.rs");
    std::fs::write(&destination, out)
        .unwrap_or_else(|error| panic!("{}: {error}", destination.display()));
}

/// Every node source under `root`, as `(module path, file)`.
///
/// One level of category directory, one file per node, which is the layout
/// `shaders/README.md` documents and `shaders.rs`'s `MODULES` table mirrors.
fn node_sources(root: &Path) -> Vec<(String, PathBuf)> {
    let mut found = Vec::new();
    let categories = std::fs::read_dir(root)
        .unwrap_or_else(|error| panic!("{}: {error}", root.display()))
        .filter_map(Result::ok);
    for category in categories {
        let directory = category.path();
        if !directory.is_dir() {
            continue;
        }
        let name = directory
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_string();
        if name == ABI_DIRECTORY {
            continue;
        }
        let files = std::fs::read_dir(&directory)
            .unwrap_or_else(|error| panic!("{}: {error}", directory.display()))
            .filter_map(Result::ok);
        for file in files {
            let path = file.path();
            if path.extension().is_none_or(|extension| extension != "wxsl") {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .unwrap_or_default();
            found.push((format!("package::{name}::{stem}"), path));
        }
    }
    found
}

// ---------------------------------------------------------------------------
// NodeDefinition, as Rust source
// ---------------------------------------------------------------------------

/// One definition as a builder chain, using the same public API a
/// hand-written node uses.
fn definition_expr(definition: &NodeDefinition) -> String {
    let NodeBody::Call(call) = &definition.body else {
        panic!("`{}` is not a call", definition.id);
    };
    let mut out = format!(
        "NodeDefinition::builder({}, {})\n            .doc({})",
        quoted(&definition.id),
        quoted(&definition.label),
        quoted(&definition.doc),
    );
    for param in &definition.generics {
        let _ = write!(out, "\n            .generic_param({})", generic_expr(param));
    }
    for declaration in &definition.macros {
        let _ = write!(out, "\n            .macro_var({})", macro_expr(declaration));
    }
    let params = call
        .params
        .iter()
        .map(socket_expr)
        .collect::<Vec<_>>()
        .join(", ");
    let function = match &call.ret {
        FunctionReturn::Value(socket) => format!(
            "WxslFunction::new({}, {}, vec![{params}], {})",
            quoted(call.module.as_str()),
            quoted(call.name.as_str()),
            socket_expr(socket),
        ),
        FunctionReturn::Struct { name, fields } => format!(
            "WxslFunction::new_struct({}, {}, vec![{params}], {}, vec![{}])",
            quoted(call.module.as_str()),
            quoted(call.name.as_str()),
            quoted(name.as_str()),
            fields
                .iter()
                .map(socket_expr)
                .collect::<Vec<_>>()
                .join(", "),
        ),
    };
    let _ = write!(out, "\n            .call({function})");
    out
}

fn generic_expr(param: &GenericParam) -> String {
    let allowed = param
        .allowed
        .iter()
        .map(type_expr)
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "GenericParam::new({}, vec![{allowed}])",
        quoted(param.name.as_str())
    )
}

fn macro_expr(declaration: &MacroDef) -> String {
    let value = match declaration.default {
        MacroValue::Flag(flag) => format!("MacroValue::Flag({flag})"),
        MacroValue::Int(value) => format!("MacroValue::Int({value})"),
        MacroValue::Float(value) => format!("MacroValue::Float({})", float(value)),
    };
    format!(
        "MacroDef::new({}, {value}, {})",
        quoted(declaration.name.as_str()),
        quoted(&declaration.doc),
    )
}

/// One socket, built in the order the setters require: the parameter it
/// carries before the default that spreads over it, since
/// `Socket::with_default` rejects a generic socket outright.
fn socket_expr(socket: &Socket) -> String {
    let mut out = format!(
        "Socket::new({}, {})",
        quoted(socket.name.as_str()),
        type_expr(&socket.ty)
    );
    if let Some(param) = &socket.generic {
        let _ = write!(out, ".generic({})", quoted(param.as_str()));
    }
    if let Some(default) = socket.default {
        let _ = write!(out, ".with_default({})", value_expr(default));
    }
    if let Some(splat) = socket.splat_default {
        let _ = write!(out, ".with_splat_default({})", float(splat));
    }
    if !socket.doc.is_empty() {
        let _ = write!(out, ".with_doc({})", quoted(&socket.doc));
    }
    out
}

fn value_expr(value: Value) -> String {
    fn components(name: &str, cells: &[f32]) -> String {
        let cells = cells.iter().copied().map(float).collect::<Vec<_>>();
        format!("Value::{name}([{}])", cells.join(", "))
    }
    match value {
        Value::Bool(flag) => format!("Value::Bool({flag})"),
        Value::I32(number) => format!("Value::I32({number})"),
        Value::U32(number) => format!("Value::U32({number})"),
        Value::F32(number) => format!("Value::F32({})", float(number)),
        Value::Vec2(cells) => components("Vec2", &cells),
        Value::Vec3(cells) => components("Vec3", &cells),
        Value::Vec4(cells) => components("Vec4", &cells),
        Value::Mat3(cells) => components("Mat3", &cells),
        Value::Mat4(cells) => components("Mat4", &cells),
    }
}

fn type_expr(ty: &ValueType) -> String {
    format!("ValueType::{ty:?}")
}

/// An `f32` as a Rust literal that reads back bit-for-bit.
///
/// `{:?}` is the shortest round-tripping form and always keeps a decimal
/// point, so it is already a float literal rather than an integer one.
fn float(value: f32) -> String {
    assert!(
        value.is_finite(),
        "a socket default of {value} has no literal"
    );
    format!("{value:?}f32")
}

/// A Rust string literal holding `text`.
fn quoted(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(character),
        }
    }
    out.push('"');
    out
}
