[package]
name = "wxsl-render"
description = "wgpu-based renderer for wxsl: pipeline abstraction with automatic forward/deferred shader variant switching."
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
wxsl-core = { workspace = true }
wxsl-lang = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
